IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'DATA_BASE_NAME')
BEGIN
    ALTER DATABASE [DATA_BASE_NAME] SET SINGLE_USER WITH ROLLBACK IMMEDIATE
    DROP DATABASE [DATA_BASE_NAME]
END
--SEP--
CREATE DATABASE [DATA_BASE_NAME] COLLATE Cyrillic_General_CI_AS;